accounts/urls.py
from django.contrib import admin
from . import views


from django.urls import include, path

from . import views
app_name = "accounts"

urlpatterns = [
    path('', views.signup,name="signup"),

    path('list', views.UserListView.as_view(),name="list"),
]

api/urls.py
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('rest-auth/', include('rest_auth.urls')),
]

customs/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


from accounts.views import *


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls")),
    path('api', include('api.urls')),
    path('', TemplateView.as_view(template_name="homepage.html")),






]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
	name = models.CharField(blank=True, max_length=255)
	email=models.CharField(max_length=100,unique=True)
	phone=models.CharField(max_length=10,default='')
	USERNAME_FIELD  = 'email'
	REQUIRED_FIELDS =['username']
	def __str__(self):
	    return self.email

api/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email','phone')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email','phone')

accounts/views.py
from rest_framework import generics
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from rest_framework.response import Response

from . import models
from . import serializers

def signup(request):
	return render(request,"reg.html")


class UserListView(generics.ListCreateAPIView):
    queryset = models.CustomUser.objects.all()
    serializer_class = serializers.UserSerializer







	

api/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/user/login.html
<html>
<body>
    <div class="col-md-6 login-form-1">
        <h3>Login</h3>
        <form class='my-ajax-form' method='POST' data-url='users/login/'>
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email *" value="" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Your Password *" value="" />
            </div>
            <div class="form-group">
                <input type="submit" class="btnSubmit" value="Login" />
            </div>
            <div class="form-group">
                <a href="#" class="ForgetPwd">Forget Password?</a>
            </div>
        </form>
    </div>
</body>'
</html>' 

templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% block title %}Homepage{% endblock %}
{% block content %}
<a href="{% url 'login' %}">login</a> |
<a href="{% url 'signup' %}">signup</a>
{% endblock %}

templates/list.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% for k in queryset %}
		{{k.username}}
		{% endfor %}
	</title>
</head>
<body>

</body>
</html>

templates/login.html
<html>
<body>
    <div class="col-md-6 login-form-1">
        <h3>Login</h3>
        <form class='my-ajax-form' method='POST' data-url='users/login/'>
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email *" value="" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Your Password *" value="" />
            </div>
            <div class="form-group">
                <input type="submit" class="btnSubmit" value="Login" />
            </div>
            <div class="form-group">
                <a href="#" class="ForgetPwd">Forget Password?</a>
            </div>
        </form>
    </div>
</body>'
</html>' 

templates/reg.html
<!DOCTYPE html>
<html>
<head>

<style type="text/css">
	form{
		background-color: powderblue;
	}
	label{
		font-size: 18px;
		color: darkred;
		font-weight: bold;

	}

	input{
		width: 340px;
	    height: 30px;
	    float: right;
	}
	button{
		width: 100px;
		height: 25px;
		background-color: black;
		color: gold;
	}
</style>
</head>
<body>
	
	<form method="POST" action="{% url 'accounts:list'%}">
		            {% csrf_token %}
<div class="row">
	<div class="col-sm-1"></div>
		<div class="col-sm-4">
 <label for="email">Email</label>
 <input type="email" name="email"><br><br>
 <label for="password">Password</label>
 <input type="password" name="password"><br><br>
 <label for="name">Name</label>
<input type="text" name="name"><br><br>
<label for="phone">phone</label>
<input type="text" name="phone"><br><br>
<label>username</label>
<input type="text" name="username">
<br>
<button type="submit">Submit</button>
</div>
<div class="col-sm-7"></div>
</div>


	</form>

</body>
</html>